version: "3"

# Run 'docker compose up' to start all containers

# Default Network

volumes:
  userdata:

services:
  db:
    container_name: jj-users
    image: postgres:12
    restart: always
    env_file:
      - .env.production
    ports:
      - 5432:5432
    volumes:
      - userdata:/var/lib/postgresql/data

  api:
    container_name: api-user
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: jj-users
      DB_PORT: 5432
    env_file:
      - .env.production
    depends_on:
      - db
