name: Publish Docker image

on:
  push:
    branches: [ prod ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  push_to_registries:
    name: Push Docker image to multiple registries
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rocioferreiro/jj-infra-user
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/user-image:latest
          
  update-server:
    name: Update Server docker image
    needs: push_to_registries
    runs-on: ubuntu-latest
    steps:
      - name: Set Production Env variables if prod is target
        run: echo "VM_IP=$PROD_IP" >> $GITHUB_ENV && echo "VM_USER=$PROD_USER" >> $GITHUB_ENV
        env: 
          PROD_IP: ${{ secrets.PROD_IP }}
          PROD_USER: ${{ secrets.PROD_USER }}
      - name: Deploy
        run: echo $SSH_PUBLIC_KEY > jj-infra-deply.pub && chmod 400 ./jj-infra-deply.pub && ssh $VM_USER@$VM_IP -i ./jj-infra-deply.pub "/scripts/restart.sh"
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          VM_IP: ${{ env.VM_IP }}
          VM_USER: ${{ env.VM_USER }}
